### ISSUE TITLE
petr runner?

### ISSUE THREAD

**Issue by uci-mars** [icssc-projects/PeterPortal#48]
![](https://github.com/wayou/t-rex-runner/blob/gh-pages/assets/screenshot.gif?raw=true)
inspired by the Google Chrome error page, source code can be found in this [repo](https://github.com/wayou/t-rex-runner)

Redesign this with Petr pixel art asset to be used as error page on PeterPortal? :)

**Comment by trishaprile** [comment]
![petr_runner](https://user-images.githubusercontent.com/43232318/81377860-24dd7a00-90bb-11ea-951f-d41e3ebb0e49.gif)

**Comment by trishaprile** [comment]
Files that were changed:
![200-disabled](https://user-images.githubusercontent.com/43232318/81378001-5eae8080-90bb-11ea-84c3-da46e15f8ff1.png)
![200-error-offline](https://user-images.githubusercontent.com/43232318/81378002-5fdfad80-90bb-11ea-8477-918b107024e9.png)
![200-offline-sprite](https://user-images.githubusercontent.com/43232318/81378004-5fdfad80-90bb-11ea-9a36-91dce7c3006d.png)
![100-disabled](https://user-images.githubusercontent.com/43232318/81378026-6a9a4280-90bb-11ea-8f4f-d030c1982c00.png)
![100-error-offline](https://user-images.githubusercontent.com/43232318/81378028-6b32d900-90bb-11ea-8ecc-97bf392b848e.png)
![100-offline-sprite](https://user-images.githubusercontent.com/43232318/81378029-6b32d900-90bb-11ea-8041-f34c69480566.png)

**Comment by uci-mars** [comment]
I love this!

I'll work on integrating it into the app asap! :)
